// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: flights.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Flights {
  public static partial class SearchFlightService
  {
    static readonly string __ServiceName = "flights.SearchFlightService";

    static readonly grpc::Marshaller<global::Flights.SearchFlightRequest> __Marshaller_flights_SearchFlightRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Flights.SearchFlightRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Flights.SearchFlightResponse> __Marshaller_flights_SearchFlightResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Flights.SearchFlightResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Flights.SearchFlightRequest, global::Flights.SearchFlightResponse> __Method_SearchFlight = new grpc::Method<global::Flights.SearchFlightRequest, global::Flights.SearchFlightResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SearchFlight",
        __Marshaller_flights_SearchFlightRequest,
        __Marshaller_flights_SearchFlightResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Flights.FlightsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchFlightService</summary>
    [grpc::BindServiceMethod(typeof(SearchFlightService), "BindService")]
    public abstract partial class SearchFlightServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SearchFlight(global::Flights.SearchFlightRequest request, grpc::IServerStreamWriter<global::Flights.SearchFlightResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SearchFlightService</summary>
    public partial class SearchFlightServiceClient : grpc::ClientBase<SearchFlightServiceClient>
    {
      /// <summary>Creates a new client for SearchFlightService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SearchFlightServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SearchFlightService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SearchFlightServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SearchFlightServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SearchFlightServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Flights.SearchFlightResponse> SearchFlight(global::Flights.SearchFlightRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchFlight(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Flights.SearchFlightResponse> SearchFlight(global::Flights.SearchFlightRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SearchFlight, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SearchFlightServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SearchFlightServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SearchFlightServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SearchFlight, serviceImpl.SearchFlight).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchFlightServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SearchFlight, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Flights.SearchFlightRequest, global::Flights.SearchFlightResponse>(serviceImpl.SearchFlight));
    }

  }
}
#endregion
