// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stays.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Stays {
  public static partial class SearchStaysService
  {
    static readonly string __ServiceName = "stays.SearchStaysService";

    static readonly grpc::Marshaller<global::Stays.SearchStaysRequest> __Marshaller_stays_SearchStaysRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Stays.SearchStaysRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Stays.SearchStaysResponse> __Marshaller_stays_SearchStaysResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Stays.SearchStaysResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Stays.SearchStaysRequest, global::Stays.SearchStaysResponse> __Method_SearchStay = new grpc::Method<global::Stays.SearchStaysRequest, global::Stays.SearchStaysResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SearchStay",
        __Marshaller_stays_SearchStaysRequest,
        __Marshaller_stays_SearchStaysResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Stays.StaysReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchStaysService</summary>
    [grpc::BindServiceMethod(typeof(SearchStaysService), "BindService")]
    public abstract partial class SearchStaysServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SearchStay(global::Stays.SearchStaysRequest request, grpc::IServerStreamWriter<global::Stays.SearchStaysResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SearchStaysService</summary>
    public partial class SearchStaysServiceClient : grpc::ClientBase<SearchStaysServiceClient>
    {
      /// <summary>Creates a new client for SearchStaysService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SearchStaysServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SearchStaysService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SearchStaysServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SearchStaysServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SearchStaysServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Stays.SearchStaysResponse> SearchStay(global::Stays.SearchStaysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SearchStay(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Stays.SearchStaysResponse> SearchStay(global::Stays.SearchStaysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SearchStay, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SearchStaysServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SearchStaysServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SearchStaysServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SearchStay, serviceImpl.SearchStay).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchStaysServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SearchStay, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Stays.SearchStaysRequest, global::Stays.SearchStaysResponse>(serviceImpl.SearchStay));
    }

  }
}
#endregion
